language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t manuelddo/learn_docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manuelddo/learn_docker-react npm run test